### ISSUE TITLE
Flag duplicate deletes across multiple files (see UNEXCOM)

### ISSUE THREAD

**Issue by pedroterzero** [pedroterzero/oxce-yaml-helper#29]
```yaml
items:
  - delete: STR_AVALANCHE_MISSILES
  - delete: STR_AVALANCHE_MISSILES
```
